services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: memgraph-mage
    ports:
      - "7687:7687"
      - "7444:7444"
    command: ["--log-level=TRACE"]

  lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    ports:
      - "3000:3000"
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687

  # comment out the following block if you don't want to run the Python script via Docker
  python:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: memgraph-python
    depends_on:
      - memgraph
    volumes:
      - ./data:/app/data
